export {default as Homepage} from "./home"
export {default as ProfilePage} from "./profile"
export {default as LoginPage} from "./Login"
export {default as RegisterPage} from "./register"
export {default as UpdatePage} from "./update"
export {default as MessengerPage} from "./messenger"